/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityRouteImport } from './routes/city'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as ApplyCodeRouteImport } from './routes/apply.$code'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ClubIndexRouteImport } from './routes/club.index'
import { Route as ClubsIndexRouteImport } from './routes/clubs.index'
import { Route as ClubsIdRouteImport } from './routes/clubs.$id'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageEventIdRouteImport } from './routes/manage.$eventId'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as MeAppliesRouteImport } from './routes/me.applies'
import { Route as MeClubRouteImport } from './routes/me.club'
import { Route as MeHostRouteImport } from './routes/me.host'
import { Route as MeProfileRouteImport } from './routes/me.profile'
import { Route as TicketCodeRouteImport } from './routes/ticket.$code'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaSlugRouteImport } from './routes/api/media.$slug'
import { Route as ApiOgSlugRouteImport } from './routes/api/og.$slug'
import { Route as ClubEditIdRouteImport } from './routes/club.edit.$id'
import { Route as ClubEventsEventIdRouteImport } from './routes/club.events.$eventId'
import { Route as ClubJoinCodeRouteImport } from './routes/club.join.$code'
import { Route as EventsSlugIndexRouteImport } from './routes/events.$slug.index'
import { Route as EventsSlugRegisterRouteImport } from './routes/events.$slug.register'
import { Route as MeEventsNewRouteImport } from './routes/me.events.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyCodeRoute = ApplyCodeRouteImport.update({
  id: '/apply/$code',
  path: '/apply/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/club/',
  path: '/club/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIdRoute = ClubsIdRouteImport.update({
  id: '/clubs/$id',
  path: '/clubs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageEventIdRoute = ManageEventIdRouteImport.update({
  id: '/manage/$eventId',
  path: '/manage/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeAppliesRoute = MeAppliesRouteImport.update({
  id: '/me/applies',
  path: '/me/applies',
  getParentRoute: () => rootRouteImport,
} as any)
const MeClubRoute = MeClubRouteImport.update({
  id: '/me/club',
  path: '/me/club',
  getParentRoute: () => rootRouteImport,
} as any)
const MeHostRoute = MeHostRouteImport.update({
  id: '/me/host',
  path: '/me/host',
  getParentRoute: () => rootRouteImport,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketCodeRoute = TicketCodeRouteImport.update({
  id: '/ticket/$code',
  path: '/ticket/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSlugRoute = ApiMediaSlugRouteImport.update({
  id: '/api/media/$slug',
  path: '/api/media/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgSlugRoute = ApiOgSlugRouteImport.update({
  id: '/api/og/$slug',
  path: '/api/og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubEditIdRoute = ClubEditIdRouteImport.update({
  id: '/club/edit/$id',
  path: '/club/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubEventsEventIdRoute = ClubEventsEventIdRouteImport.update({
  id: '/club/events/$eventId',
  path: '/club/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubJoinCodeRoute = ClubJoinCodeRouteImport.update({
  id: '/club/join/$code',
  path: '/club/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/events/$slug/',
  path: '/events/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRegisterRoute = EventsSlugRegisterRouteImport.update({
  id: '/events/$slug/register',
  path: '/events/$slug/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MeEventsNewRoute = MeEventsNewRouteImport.update({
  id: '/me/events/new',
  path: '/me/events/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/messages': typeof MessagesRoute
  '/tickets': typeof TicketsRoute
  '/apply/$code': typeof ApplyCodeRoute
  '/chat/$id': typeof ChatIdRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/manage/$eventId': typeof ManageEventIdRoute
  '/me/applies': typeof MeAppliesRoute
  '/me/club': typeof MeClubRoute
  '/me/host': typeof MeHostRoute
  '/me/profile': typeof MeProfileRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/users/$id': typeof UsersIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/club/': typeof ClubIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/me/': typeof MeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$slug': typeof ApiMediaSlugRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/club/edit/$id': typeof ClubEditIdRoute
  '/club/events/$eventId': typeof ClubEventsEventIdRoute
  '/club/join/$code': typeof ClubJoinCodeRoute
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/me/events/new': typeof MeEventsNewRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/messages': typeof MessagesRoute
  '/tickets': typeof TicketsRoute
  '/apply/$code': typeof ApplyCodeRoute
  '/chat/$id': typeof ChatIdRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/manage/$eventId': typeof ManageEventIdRoute
  '/me/applies': typeof MeAppliesRoute
  '/me/club': typeof MeClubRoute
  '/me/host': typeof MeHostRoute
  '/me/profile': typeof MeProfileRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/users/$id': typeof UsersIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/club': typeof ClubIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/manage': typeof ManageIndexRoute
  '/me': typeof MeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$slug': typeof ApiMediaSlugRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/club/edit/$id': typeof ClubEditIdRoute
  '/club/events/$eventId': typeof ClubEventsEventIdRoute
  '/club/join/$code': typeof ClubJoinCodeRoute
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/me/events/new': typeof MeEventsNewRoute
  '/events/$slug': typeof EventsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/messages': typeof MessagesRoute
  '/tickets': typeof TicketsRoute
  '/apply/$code': typeof ApplyCodeRoute
  '/chat/$id': typeof ChatIdRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/manage/$eventId': typeof ManageEventIdRoute
  '/me/applies': typeof MeAppliesRoute
  '/me/club': typeof MeClubRoute
  '/me/host': typeof MeHostRoute
  '/me/profile': typeof MeProfileRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/users/$id': typeof UsersIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/club/': typeof ClubIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/me/': typeof MeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$slug': typeof ApiMediaSlugRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/club/edit/$id': typeof ClubEditIdRoute
  '/club/events/$eventId': typeof ClubEventsEventIdRoute
  '/club/join/$code': typeof ClubJoinCodeRoute
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/me/events/new': typeof MeEventsNewRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/city'
    | '/login'
    | '/lookup'
    | '/messages'
    | '/tickets'
    | '/apply/$code'
    | '/chat/$id'
    | '/clubs/$id'
    | '/manage/$eventId'
    | '/me/applies'
    | '/me/club'
    | '/me/host'
    | '/me/profile'
    | '/ticket/$code'
    | '/users/$id'
    | '/verify/$token'
    | '/club/'
    | '/clubs/'
    | '/manage/'
    | '/me/'
    | '/api/auth/$'
    | '/api/media/$slug'
    | '/api/og/$slug'
    | '/club/edit/$id'
    | '/club/events/$eventId'
    | '/club/join/$code'
    | '/events/$slug/register'
    | '/me/events/new'
    | '/events/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/city'
    | '/login'
    | '/lookup'
    | '/messages'
    | '/tickets'
    | '/apply/$code'
    | '/chat/$id'
    | '/clubs/$id'
    | '/manage/$eventId'
    | '/me/applies'
    | '/me/club'
    | '/me/host'
    | '/me/profile'
    | '/ticket/$code'
    | '/users/$id'
    | '/verify/$token'
    | '/club'
    | '/clubs'
    | '/manage'
    | '/me'
    | '/api/auth/$'
    | '/api/media/$slug'
    | '/api/og/$slug'
    | '/club/edit/$id'
    | '/club/events/$eventId'
    | '/club/join/$code'
    | '/events/$slug/register'
    | '/me/events/new'
    | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/city'
    | '/login'
    | '/lookup'
    | '/messages'
    | '/tickets'
    | '/apply/$code'
    | '/chat/$id'
    | '/clubs/$id'
    | '/manage/$eventId'
    | '/me/applies'
    | '/me/club'
    | '/me/host'
    | '/me/profile'
    | '/ticket/$code'
    | '/users/$id'
    | '/verify/$token'
    | '/club/'
    | '/clubs/'
    | '/manage/'
    | '/me/'
    | '/api/auth/$'
    | '/api/media/$slug'
    | '/api/og/$slug'
    | '/club/edit/$id'
    | '/club/events/$eventId'
    | '/club/join/$code'
    | '/events/$slug/register'
    | '/me/events/new'
    | '/events/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityRoute: typeof CityRoute
  LoginRoute: typeof LoginRoute
  LookupRoute: typeof LookupRoute
  MessagesRoute: typeof MessagesRoute
  TicketsRoute: typeof TicketsRoute
  ApplyCodeRoute: typeof ApplyCodeRoute
  ChatIdRoute: typeof ChatIdRoute
  ClubsIdRoute: typeof ClubsIdRoute
  ManageEventIdRoute: typeof ManageEventIdRoute
  MeAppliesRoute: typeof MeAppliesRoute
  MeClubRoute: typeof MeClubRoute
  MeHostRoute: typeof MeHostRoute
  MeProfileRoute: typeof MeProfileRoute
  TicketCodeRoute: typeof TicketCodeRoute
  UsersIdRoute: typeof UsersIdRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  ClubIndexRoute: typeof ClubIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  ManageIndexRoute: typeof ManageIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaSlugRoute: typeof ApiMediaSlugRoute
  ApiOgSlugRoute: typeof ApiOgSlugRoute
  ClubEditIdRoute: typeof ClubEditIdRoute
  ClubEventsEventIdRoute: typeof ClubEventsEventIdRoute
  ClubJoinCodeRoute: typeof ClubJoinCodeRoute
  EventsSlugRegisterRoute: typeof EventsSlugRegisterRoute
  MeEventsNewRoute: typeof MeEventsNewRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$code': {
      id: '/apply/$code'
      path: '/apply/$code'
      fullPath: '/apply/$code'
      preLoaderRoute: typeof ApplyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/club'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$id': {
      id: '/clubs/$id'
      path: '/clubs/$id'
      fullPath: '/clubs/$id'
      preLoaderRoute: typeof ClubsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$eventId': {
      id: '/manage/$eventId'
      path: '/manage/$eventId'
      fullPath: '/manage/$eventId'
      preLoaderRoute: typeof ManageEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/applies': {
      id: '/me/applies'
      path: '/me/applies'
      fullPath: '/me/applies'
      preLoaderRoute: typeof MeAppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/club': {
      id: '/me/club'
      path: '/me/club'
      fullPath: '/me/club'
      preLoaderRoute: typeof MeClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/host': {
      id: '/me/host'
      path: '/me/host'
      fullPath: '/me/host'
      preLoaderRoute: typeof MeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$code': {
      id: '/ticket/$code'
      path: '/ticket/$code'
      fullPath: '/ticket/$code'
      preLoaderRoute: typeof TicketCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$slug': {
      id: '/api/media/$slug'
      path: '/api/media/$slug'
      fullPath: '/api/media/$slug'
      preLoaderRoute: typeof ApiMediaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$slug': {
      id: '/api/og/$slug'
      path: '/api/og/$slug'
      fullPath: '/api/og/$slug'
      preLoaderRoute: typeof ApiOgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/edit/$id': {
      id: '/club/edit/$id'
      path: '/club/edit/$id'
      fullPath: '/club/edit/$id'
      preLoaderRoute: typeof ClubEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/events/$eventId': {
      id: '/club/events/$eventId'
      path: '/club/events/$eventId'
      fullPath: '/club/events/$eventId'
      preLoaderRoute: typeof ClubEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/join/$code': {
      id: '/club/join/$code'
      path: '/club/join/$code'
      fullPath: '/club/join/$code'
      preLoaderRoute: typeof ClubJoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/events/$slug'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/register': {
      id: '/events/$slug/register'
      path: '/events/$slug/register'
      fullPath: '/events/$slug/register'
      preLoaderRoute: typeof EventsSlugRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/events/new': {
      id: '/me/events/new'
      path: '/me/events/new'
      fullPath: '/me/events/new'
      preLoaderRoute: typeof MeEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityRoute: CityRoute,
  LoginRoute: LoginRoute,
  LookupRoute: LookupRoute,
  MessagesRoute: MessagesRoute,
  TicketsRoute: TicketsRoute,
  ApplyCodeRoute: ApplyCodeRoute,
  ChatIdRoute: ChatIdRoute,
  ClubsIdRoute: ClubsIdRoute,
  ManageEventIdRoute: ManageEventIdRoute,
  MeAppliesRoute: MeAppliesRoute,
  MeClubRoute: MeClubRoute,
  MeHostRoute: MeHostRoute,
  MeProfileRoute: MeProfileRoute,
  TicketCodeRoute: TicketCodeRoute,
  UsersIdRoute: UsersIdRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  ClubIndexRoute: ClubIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  ManageIndexRoute: ManageIndexRoute,
  MeIndexRoute: MeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaSlugRoute: ApiMediaSlugRoute,
  ApiOgSlugRoute: ApiOgSlugRoute,
  ClubEditIdRoute: ClubEditIdRoute,
  ClubEventsEventIdRoute: ClubEventsEventIdRoute,
  ClubJoinCodeRoute: ClubJoinCodeRoute,
  EventsSlugRegisterRoute: EventsSlugRegisterRoute,
  MeEventsNewRoute: MeEventsNewRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
